name: Debug R CMD build
on:
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Ollama
        uses: ai-action/setup-ollama@v1
        
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
          
      - name: R CMD build
        run: |
          echo "=== Running R CMD build ==="
          R CMD build . 